# Elixir CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-elixir/ for more details
version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: defactosoftware/elixir
        environment:
          MIX_ENV: test
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-dependency-cache-{{ checksum "mix.lock" }}
            - v2-dependency-cache
      - run: mix local.hex --force
      - run: mix local.rebar --force
      - run: mix deps.get
      - run: mix compile --warnings-as-errors
      - run: mix dialyzer
      - run: mix credo
      - run: mix coveralls.json
      - run: bash <(curl -s https://codecov.io/bash) -t "$CODECOV_KEY"
      - save_cache:
          key: v2-dependency-cache-{{ checksum "mix.lock" }}
          paths:
            - deps
            - _build
            - ~/.mix
